name: creative_movers
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter: 
    sdk: flutter
  # in_app_update: ^3.0.0
  flutter_svg: ^0.23.0+1
  modal_bottom_sheet: ^2.0.0
  pin_code_fields: ^7.3.0
  group_radio_button: ^1.1.0
  dotted_border: ^2.0.0+1
  intl: ^0.17.0
  dropdown_search: ^2.0.1
  image_stack: ^2.1.0
  # syncfusion_flutter_datepicker: ^20.1.50
  cupertino_icons: ^1.0.2
  flutter_localizations: 
    sdk: flutter
  google_nav_bar: ^5.0.5
  flutter_bloc: ^8.0.1
  flutter_native_splash:
  dio: ^4.0.4
  shared_preferences: ^2.0.13
  pretty_dio_logger: ^1.2.0-beta-1
  equatable: ^2.0.3
  form_field_validator: ^1.1.0
  get_it: ^7.2.0
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  fluttertoast: ^8.0.8
  file_picker: ^4.2.7
  path: ^1.8.0
  flutter_stripe: ^2.2.0
  either_dart: ^0.1.4
  video_player: ^2.2.18
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.9
  scrollable_positioned_list: ^0.2.3
  chewie: ^1.3.0
  # font_awesome_flutter: ^9.2.0
  sembast: ^3.1.2
  page_transition: ^2.0.5
  cached_network_image: ^3.2.0
  flutter_custom_tabs: ^1.0.4
  status_view: ^0.0.2
  story_view: ^0.13.2
  csc_picker: ^0.2.6
  image_picker: ^0.8.4+10
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
  firebase_core: ^1.14.1
  firebase_messaging: ^11.2.13
  firebase_remote_config: ^2.0.4
  cloud_firestore: ^3.1.17
  firebase_analytics: ^9.1.5
  flutter_local_notifications: ^9.4.0
  uuid: ^3.0.6
  grouped_list: ^4.1.0
  agora_rtc_engine: ^5.1.0
  agora_rtm: ^1.1.0
  permission_handler: ^9.2.0
  expandable_text: ^2.3.0
  native_linkify: ^0.0.1
  any_link_preview: ^2.0.7
  camera: ^0.9.4+21
  audioplayers: ^0.20.1
  flutter_reaction_button: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pngs/ic_app_logo.png"

# The following section is specific to Flutter.
flutter:
  generate: true
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/segoe/segoe_regular.ttf
        - asset: assets/fonts/segoe/segoe_bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/poppins_regular.ttf
        - asset: assets/fonts/poppins/poppins_bold.ttf
        - asset: assets/fonts/poppins/poppins_medium.ttf
   
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
    - assets/pngs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #    fonts:
  #       - family: Segoe
  #         fonts:
  #          - asset: fonts/segoe_regular.ttf
  #          - asset: fonts/Segoe-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
